title: "Taskmania"
theme: jekyll-theme-midnight

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2021S1-CS2103T-W10-3"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
